mobs:register_mob("awesome_monsters:mummy", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	reach = 2,
	damage = 3,
	hp_min = 15,
	hp_max = 20,
	armor = 100,
	collisionbox = {-0.3, 0.0, -0.3, 0.3, 1.7, 0.3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {
		{"awesome_monsters_mummy.png"},
	},
	blood_texture = "default_paper.png",
	makes_footstep_sound = true,
	sounds = {
		random = "awesome_monsters_groan",
	},
	walk_velocity = 1,
	run_velocity = 3,
	jump = true,
	view_range = 15,
	floats = 1,
	drops = {
		{name = "default:paper", chance = 3, min = 3, max = 5},
	},
	water_damage = 0,
	lava_damage = 0,
	fire_damage = 0,
	light_damage = 0,
	animation = {
		stand_start = 0,
		stand_end = 79,
		stand_speed = 30,
		walk_start = 168,
		walk_end = 187,
		walk_speed = 30,
		run_start = 168,
		run_end = 187,
		run_speed = 30,
		punch_start = 189,
		punch_end = 198,
		punch_speed = 30,
		die_start = 162,
		die_end = 166,
		die_speed = 0.8
	},	
})

mobs:spawn({
	name = "awesome_monsters:mummy",
	nodes = {"default:desert_sand", "default:desert_stone"},
	min_light = 0,
	max_light = 15,
	chance = 5000,
	active_object_count = 3,
	min_height = 0,
	day_toggle = true,
})